name: Scan chrome and firefox with docker

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan pages
        run: docker build . && docker-compose run scan-chrome

  scan-firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scan pages
        run: docker build . && docker-compose run scan-firefox
